// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: delete_feed_follow.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const unfollow = `-- name: Unfollow :exec
DELETE FROM feed_follows
USING feeds, users
WHERE feeds.id = feed_follows.feed_id
AND users.id = feed_follows.user_id
AND users.id = $1
`

func (q *Queries) Unfollow(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, unfollow, id)
	return err
}
